services:
  db:
    image: postgres:15
    container_name: ady_postgres
    restart: always
    environment:
      POSTGRES_USER: mytam_vankhanh
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ady_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: ady_minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata_new:
  minio_data: