services:
  db:
    image: postgres:15
    container_name: ady_postgres
    restart: always
    environment:
      POSTGRES_USER: mytam_vankhanh
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ady_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata_new:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata_new: